# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ViewModelType' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViewModelType
pod 'RxSwift'
pod 'RxCocoa'
  target 'ViewModelTypeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ViewModelTypeUITests' do
    # Pods for testing
  end

end
