# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'loginValidation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for loginValidation
pod 'MaterialComponents/TextControls+OutlinedTextFields'
pod 'RxSwift'
pod 'RxCocoa'
pod 'MaterialComponents/Buttons'
end
